export const SET_HOMES_SUCCESS = 'SET_HOMES_SUCCESS';
export const SET_HOMES_HAS_MORE = 'SET_HOMES_HAS_MORE';
export const SET_HOMES_ERROR = 'SET_HOMES_ERROR';
export const SET_HOMES_LOADING = 'SET_HOMES_LOADING';
export const CLEAR_HOMES = 'CLEAR_HOMES';
export const SET_QUERY_PARAMS_LENGTH = 'SET_QUERY_PARAMS_LENGTH';
