export const SET_PRELOADED_HOMES = 'SET_PRELOADED_HOMES';
export const FETCH_HOMES_SUCCESS = 'SET_HOMES_SUCCESS';
export const FETCH_HOMES_LOADING = 'SET_HOMES_LOADING';
export const FETCH_HOMES_ERROR = 'SET_HOMES_ERROR';
export const CLEAR_HOMES = 'CLEAR_HOMES';
