import Head from 'next/head';
import Image from 'next/image';
import HomeCategories from '../components/HomeCategories';
import Layout from '../components/Layout';
import classes from '../styles/home.module.scss';

export default function Home() {
  return (
    <Layout home>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <section className={classes.hero}></section>

      <HomeCategories />
    </Layout>
  );
}
